services:
  test_master:
    build:           # 指向當前目錄下的 Dockerfile
      dockerfile: ./dockerfile.basic
    container_name: my_ubuntu_test
    network: host
    privileged: true
    # ports:
    #   - "%HOST_PORT%:22"     # Mac 2222 -> 容器 22 (SSH)
    restart: always
    volumes:
      # - ${HOME}/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ${HOME}/.ssh/id_%KEY_TYPE%.pub:/root/.ssh/authorized_keys:ro
      - ${HOME}/data:/mnt
      - test_master_share_volume:/home/jenkins
volumes:
  test_master_share_volume: