services:
  test_master:
    build:
      dockerfile: Dockerfile         # 指向當前目錄下的 Dockerfile
    image: spx_master:v1.25.1
    stdin_open: true
    tty: true
    restart: unless-stopped
    # ports:
    #   - "%HOST_PORT%:%HOST_PORT%"
    network_mode: "host"
    container_name: my_spx_master_v1.25
    privileged: true  # 執行 rpcbind 建議開啟
    environment:
      - DISPLAY=:0
      - GIT_ACCOUNT=%GIT_ACCOUNT%
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ${HOME}/Desktop/spx_sandbox/output:/output
      # - ${HOME}/Desktop/spx_sandbox/results:/myvol
      # - ${HOME}/Desktop/spx_taas_v1.25/Tests:/Tests