services:
  test_master:
    build:
      dockerfile: Dockerfile         # 指向當前目錄下的 Dockerfile
    image: spx_master:v1.25
    container_name: my_spx_master_v1.25
    hostname: spx_master
    network_mode: "host"
    stdin_open: true
    tty: true
    restart: no
    # for ssh connection, we need to use host network or map port 22 to a host port
    # ports:
    #   - "%HOST_PORT%:22"
    privileged: true  # 執行 rpcbind 建議開啟
    environment:
      - DISPLAY=:0
      - GIT_ACCOUNT=%GIT_ACCOUNT%
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - %SHARE_VOLUMES_OUTPUT%:/output
      - %SHARE_VOLUMES_MYVOL%:/myvol
      # - ${HOME}/Desktop/spx_taas_v1.25/Tests:/Tests